# --------------------------------------------------------------------
# Pre-commit configuration file | https://pre-commit.com/
#
# You'll need to install pre-commit to use this file.
# pre-commit install
#
# To run pre-commit check without making a commit:
# pre-commit run --all-files
#
# Update pre-commit hook versions:
# pre-commit autoupdate
# --------------------------------------------------------------------

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-ast
  - id: fix-byte-order-marker
  - id: check-case-conflict
  - id: trailing-whitespace
  - id: mixed-line-ending
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: detect-aws-credentials
  - id: detect-private-key

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.1
  hooks:
  - id: bandit
    args:
      - -r
      - -s
      # https://bandit.readthedocs.io/en/latest/blacklists/blacklist_imports.html
      - B402,B321

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

- repo: https://github.com/markdownlint/markdownlint
  rev: v0.11.0
  hooks:
  - id: markdownlint